### ISSUE TITLE
Issue identified while building the maven project in a Linux distribution

### ISSUE THREAD

**Issue by vborrego** [Altran-PT-GDC/Robot-Framework-Test-FX-Library#1]
Hi. 

While trying to build the library I got the following issues:

Test Capture Screen                                                   | FAIL |
Environment variable '%{USERPROFILE}' not found.

[report.zip](https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/files/1707089/report.zip)
Test Erase Text                                                       | FAIL |
The text is diferent - Default t

The environment variable USERPROFILE usually only exists in Windows environments. 
In [OperatingSystem](http://robotframework.org/robotframework/latest/libraries/OperatingSystem.html) it's mentioned that the tilde character can be expanded to the current home directory.

**Comment by jdagomes** [comment]
Hello,

I will look into the issue, can you tell me what Linux distribution you are using?

**Comment by vborrego** [comment]
I'm using Slackware Linux. For a Debian/Ubuntu/CentOS  system I think that the issue would also occur.

The attached patch has some changes I made that allowed the failed tests to pass.

[patch.zip](https://github.com/Altran-PT-GDC/Robot-Framework-Test-FX-Library/files/1707618/patch.zip)

**Comment by jdagomes** [comment]
Thank you for the change suggestion. I will test the changes.

Would you like to create a pull request with your changes or you want me to commit them?

**Comment by vborrego** [comment]
After the tests are done and if they are successful you can commit them.

**Comment by jdagomes** [comment]
Hello,

I added the fixes to the master branch. Tested it in Ubuntu and worked fine.

Used ${CURDIR}/screenshots to "capture screen" test case as new screenshot location.

Thank you for your support.
