### ISSUE TITLE
Add a simple Demo to the repository

### ISSUE THREAD

**Issue by codecube** [Altran-PT-GDC/Robot-Framework-Test-FX-Library#3]
We should add a simple demo to the repository, that could be downloaded in a .zip file, 
The RF-TestFX-Library_Demo.zip should contain: A simple compiled JavaFX app (demo.jar) with a button and a text field, a single FR script (RF-TestFX-Library_Demo.txt) and a Readme.txt with instructions, would sufice.

**Comment by jdagomes** [comment]
A demo zip file was added in the 1.0.0 release, which includes a custom start script, a sample JavaFx application, a robot framework test case and instructions on how to run the demo.
