### ISSUE TITLE
Add support for the remote library API.

### ISSUE THREAD

**Issue by aaltat** [Altran-PT-GDC/Robot-Framework-Test-FX-Library#4]
It would be useful to run Robot Framework from Python and use this library over the remote library API: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#remote-library-interface

There is already a Java Remote Server available for Robot Framework: https://github.com/ombre42/jrobotremoteserver

And example remote swing library bundles a nice example how Java Remote Server can be used: https://github.com/robotframework/remoteswinglibrary

**Comment by codecube** [comment]
Thank you @aaltat! That is really nice feature to add!

**Comment by alejandro-serrano** [comment]
Hi @codecube !

I have been there before. To make it and keep it simple start with the simplistic approach documented in the Getting started section.
- https://github.com/ombre42/jrobotremoteserver/wiki/Getting-Started

Once you get it, just try to connect your library thorugh the remote library interface provided by Robot Framework and mentioned by @aaltat and you will get it :)

There is just one issue I have faced in the past when trying to get logs from the System Under Test, the actual Java Remote Library (in this case will be yours) and the remote library written in other language (e.g. Python)

You can find a ton of details about how I was able to solve it here:
https://groups.google.com/forum/#!topic/robotframework-users/wgrE6jR9Y90/discussion

I hope you find this information useful.
Have fun!
Alejandro Serrano.

**Comment by jdagomes** [comment]
Hello!

Thank you for all the help. We've added the possibility to run the library remotely in the latest version.

This issue will be closed now.

Thank you all for your help and support.
