### ISSUE TITLE
Consider clear git cache

### ISSUE THREAD

**Issue by brunomarioalmeida** [Altran-PT-GDC/Robot-Framework-Test-FX-Library#6]
Hi All,

Checking project root directory size, you get around 39Mb. Without .git directory you have about 1Mb. So, I thing we all take benefit from getting a lighter version of this project if you can git clean it.
Here's a link with a suggestion: 
https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git

I understand this happening by adding non version-able files as jars at first and then deleting them. But they always get into your way if you do not take any action.

**Comment by jdagomes** [comment]
Thank you for the suggestion.

I will take a look into it.

**Comment by jdagomes** [comment]
Problem solved.

Thanks for the hint.
